Update job-results.yml

diff --git a/.github/workflows/job-results.yml b/.github/workflows/job-results.yml
--- a/.github/workflows/job-results.yml
+++ b/.github/workflows/job-results.yml
@@ -32,4 +32,7 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ failure() }}
     steps:
-     - run: echo "Failure"
+     - if: ${{needs.setup.result == 'failure'}}
+       run: |
+        echo "Failure"
+        exit 1
